### ISSUE TITLE
GCP - Implement Istio Service Mesh

### ISSUE THREAD

**Issue by ianstanton** [astronomer/terraform#2]
Add Istio Service Mesh to GKE. More information on Istio [here](https://istio.io/docs/concepts/what-is-istio/).

**Comment by ianstanton** [comment]
Added the following to our `google_container_cluster` resource:
```
addons_config {
  istio_config {
    disabled = false
  }
} 
```
Followed [this guide](https://cloud.google.com/istio/docs/istio-on-gke/installing) to configure `istio-proxy` sidecars for each astronomer pod.

**Comment by ianstanton** [comment]
Istio creates its own kubernetes namespace when enabled.  Here is a look at the services and pods that live in the `istio-system` namespace:

```
$ kubectl get service -n istio-system
NAME                     TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)                                                                                                                   AGE
istio-citadel            ClusterIP      10.98.8.176    <none>          8060/TCP,9093/TCP                                                                                                         66m
istio-egressgateway      ClusterIP      10.98.7.49     <none>          80/TCP,443/TCP                                                                                                            66m
istio-galley             ClusterIP      10.98.5.143    <none>          443/TCP,9093/TCP                                                                                                          66m
istio-ingressgateway     LoadBalancer   10.98.11.218   35.245.199.32   80:31003/TCP,443:30465/TCP,31400:30893/TCP,15011:30562/TCP,8060:32157/TCP,853:31477/TCP,15030:30436/TCP,15031:31410/TCP   66m
istio-pilot              ClusterIP      10.98.14.205   <none>          15010/TCP,15011/TCP,8080/TCP,9093/TCP                                                                                     66m
istio-policy             ClusterIP      10.98.13.197   <none>          9091/TCP,15004/TCP,9093/TCP                                                                                               66m
istio-sidecar-injector   ClusterIP      10.98.12.243   <none>          443/TCP                                                                                                                   66m
istio-telemetry          ClusterIP      10.98.0.87     <none>          9091/TCP,15004/TCP,9093/TCP,42422/TCP                                                                                     66m
promsd                   ClusterIP      10.98.9.216    <none>          9090/TCP                                                                                                                  66m
```

```
$ kubectl get pods -n istio-system
NAME                                      READY   STATUS      RESTARTS   AGE
istio-citadel-6995f7bd9-lh78m             1/1     Running     0          72m
istio-cleanup-secrets-k2nn9               0/1     Completed   0          72m
istio-egressgateway-57b96d87bd-fk5q5      1/1     Running     0          72m
istio-galley-6d7dd498f6-24k4g             1/1     Running     0          72m
istio-ingressgateway-ddd557db7-mmjgg      1/1     Running     0          72m
istio-pilot-5765d76b8c-l6frm              2/2     Running     0          72m
istio-policy-5b47b88467-km7fx             2/2     Running     0          72m
istio-sidecar-injector-6b9fbbfcf6-6sdtf   1/1     Running     0          72m
istio-telemetry-65dcd9ff85-fkjsp          2/2     Running     0          72m
promsd-7b49dcb96c-p5sd6                   2/2     Running     1          72m
```

**Comment by ianstanton** [comment]
Here is a look at the astronomer pods after deployment with Istio enabled:
```
$ kubectl get po -n astronomer
NAME                                            READY   STATUS                  RESTARTS   AGE
astro-alertmanager-0                            1/2     Running                 0          10m
astro-cli-install-844fd4f66f-pnfd9              2/2     Running                 7          10m
astro-commander-85b5d9b55f-xvmgg                1/2     CrashLoopBackOff        6          10m
astro-elasticsearch-client-799f8f647c-99f9h     1/2     Running                 5          10m
astro-elasticsearch-client-799f8f647c-pppt6     1/2     Running                 5          10m
astro-elasticsearch-data-0                      2/2     Running                 0          10m
astro-elasticsearch-data-1                      2/2     Running                 0          10m
astro-elasticsearch-exporter-7bdbf66cb8-lfm5j   0/2     Init:CrashLoopBackOff   6          10m
astro-elasticsearch-master-0                    2/2     Running                 0          10m
astro-elasticsearch-master-1                    2/2     Running                 0          10m
astro-elasticsearch-master-2                    2/2     Running                 0          10m
astro-elasticsearch-nginx-5678dd764c-vqtrc      2/2     Running                 0          10m
astro-fluentd-cdcf8                             2/2     Running                 1          10m
astro-fluentd-mrbtc                             2/2     Running                 1          10m
astro-fluentd-qf9jf                             2/2     Running                 2          10m
astro-grafana-6c99d79dcf-pbdlg                  1/2     CrashLoopBackOff        6          10m
astro-houston-7cb77f7957-dzcgv                  1/2     CrashLoopBackOff        6          10m
astro-kibana-66fcf97f98-wd75d                   2/2     Running                 0          10m
astro-kube-replicator-59d4fcdd45-4pnfp          2/2     Running                 2          10m
astro-kube-state-b96d4569-tv4n7                 1/2     CrashLoopBackOff        6          10m
astro-nginx-658448ccd-z7mlx                     1/2     CrashLoopBackOff        6          10m
astro-nginx-default-backend-54bdc94998-4tcnt    1/2     CrashLoopBackOff        6          10m
astro-orbit-bdcdc8c8-7rtsj                      1/2     CrashLoopBackOff        7          10m
astro-prisma-7f9f9896b4-l2zjd                   1/2     CrashLoopBackOff        6          10m
astro-prometheus-0                              1/2     CrashLoopBackOff        7          10m
astro-registry-6dff774dc4-flg9d                 1/2     CrashLoopBackOff        7          10m
```

**Comment by ianstanton** [comment]
Here are logs from `houston` and `commander`:
```
$ kubectl logs astro-houston-7cb77f7957-dzcgv -c astro-houston -n astronomer
Waiting for host: astro-prisma 4466
Received response from: astro-prisma 4466

> houston-api@1.0.0 serve /houston
> prisma deploy && node dist/index.js


Creating stage default for service houston... !
 ▸    'ECONNRESET': request to http://astro-prisma:4466/management failed,
 ▸    reason: socket hang up

Get in touch if you need help: https://spectrum.chat/prisma
To get more detailed output, run $ export DEBUG="*"
raven@2.6.4 alert: failed to send exception to sentry: Client network socket disconnected before secure TLS connection was established
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! houston-api@1.0.0 serve: `prisma deploy && node dist/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the houston-api@1.0.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-19T19_55_05_065Z-debug.log
```

```
$ kubectl logs astro-commander-85b5d9b55f-xvmgg -c astro-commander -n astronomer
time="2019-05-19T20:14:19Z" level=info msg="Starting commander" function=start package=cmd
time="2019-05-19T20:14:19Z" level=debug msg="Getting KubeConfig" function=GetKubeConfig package=kubernetes
time="2019-05-19T20:14:19Z" level=debug msg="Using in-cluster config" function=GetKubeConfig package=kubernetes
time="2019-05-19T20:14:19Z" level=debug msg="Creating Kubernetes client" function=NewKubeProvisioner package=kubernetes
[/root/.helm /root/.helm/repository /root/.helm/repository/cache /root/.helm/repository/local /root/.helm/plugins /root/.helm/starters /root/.helm/cache/archive]
panic: open /root/.helm/repository/cache/astronomer-ee-index.yaml: no such file or directory

goroutine 1 [running]:
github.com/astronomerio/commander/helm.New(0xc0004cb230, 0xc000044044, 0x1a, 0x0)
    /usr/lib/go/src/github.com/astronomerio/commander/helm/client.go:69 +0x359
github.com/astronomerio/commander/cmd.start()
    /usr/lib/go/src/github.com/astronomerio/commander/cmd/root.go:54 +0x204
github.com/astronomerio/commander/cmd.glob..func1(0x556800b205e0, 0x556800ba5600, 0x0, 0x0)
    /usr/lib/go/src/github.com/astronomerio/commander/cmd/root.go:27 +0x22
github.com/astronomerio/commander/vendor/github.com/spf13/cobra.(*Command).execute(0x556800b205e0, 0xc00003a1b0, 0x0, 0x0, 0x556800b205e0, 0xc00003a1b0)
    /usr/lib/go/src/github.com/astronomerio/commander/vendor/github.com/spf13/cobra/command.go:702 +0x2d5
github.com/astronomerio/commander/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x556800b205e0, 0x7, 0x5567ffa2dfc0, 0x5567ffce8be0)
    /usr/lib/go/src/github.com/astronomerio/commander/vendor/github.com/spf13/cobra/command.go:783 +0x2de
github.com/astronomerio/commander/vendor/github.com/spf13/cobra.(*Command).Execute(0x556800b205e0, 0x0, 0x7)
    /usr/lib/go/src/github.com/astronomerio/commander/vendor/github.com/spf13/cobra/command.go:736 +0x2d
main.main()
    /usr/lib/go/src/github.com/astronomerio/commander/main.go:11 +0x2f
```

**Comment by ianstanton** [comment]
Update:
* Followed guidance from https://github.com/istio/istio/issues/7776#issuecomment-412197907 for `istio` + `nginx` configuration
* Added the following to `charts/astronomer/templates/ingress.yaml`:
```
nginx.ingress.kubernetes.io/service-upstream: "true"
nginx.ingress.kubernetes.io/upstream-vhost: {{ .Release.Name }}-nginx.astronomer.svc.cluster.local
```
* Added the following to `charts/nginx/templates/nginx-deployment.yaml` to skip sidecar injection in `nginx` pod:
```
traffic.sidecar.istio.io/includeInboundPorts: ""
sidecar.istio.io/inject: "false"
```

**Comment by ianstanton** [comment]
Added the following to allow communication with cloud sql database:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cloud-sql
spec:
  hosts:
  - cloud-sql.tcp.svc
  addresses:
  - $CLOUD_SQL_IP/32
  ports:
  - number: 5432
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
  resolution: STATIC
  endpoints:
  - address: $CLOUD_SQL_IP
```

**Comment by ianstanton** [comment]
Update:
* Using permissive mTLS
* Able to reach orbit and sign in
* When creating airflow instances, namespace is created but pods do not deploy
* `elasticsearch-client` pods cannot connect to `elasticsearch-master`
* `registry` can't connect to bucket

**Comment by ianstanton** [comment]
Found that there is an option to enable all egress traffic.  This option is flagged during installation and is NOT an option for GKE managed Istio:

>"Istio has an installation option, global.outboundTrafficPolicy.mode, that configures the sidecar handling of external services, that is, those services that are not defined in Istio’s internal service registry. If this option is set to ALLOW_ANY, the Istio proxy lets calls to unknown services pass through." https://istio.io/docs/tasks/traffic-management/egress/#calling-external-services-directly

This is great, but we run into limitations because we have GKE managing the istio install:

>"Because Istio on GKE controls how your control plane is installed and upgraded, it does not let you edit most of the control plane configuration settings provided in our installation." - https://cloud.google.com/istio/docs/istio-on-gke/overview

We should easily be able to install istio via helm instead of GKE addon

**Comment by ianstanton** [comment]
Installed Istio via helm on fresh cluster:
* Using permissive mTLS
* `global.outboundTrafficPolicy.mode: ALLOW_ALL`
* No need to create `serviceEntry` or `nginx` without sidecar
* Able to:
  * Access Orbit
  * Sign in
  * Create airflow instance, new namespace creates, pods spin up
  * Navigate to Airflow webserver
* All pods 2/2 with sidecar except:
  * fluentd pods failing healthcheck?
  * registry pod

**Comment by schnie** [comment]
This sounds pretty good eh? Was fluentd having trouble with gke istio?

**Comment by ianstanton** [comment]
> This sounds pretty good eh? Was fluentd having trouble with gke istio?

Yeah, I'd be much happier going this route. We get full features, latest version, and can manage / configure with helm. Actually the fluentd pods had no problems with GKE Istio...

**Comment by ianstanton** [comment]
Update:
* Registry pod 2/2 - secret was created improperly.

**Comment by ianstanton** [comment]
Here is a list of all available options for an Istio installation.  We'll want to review these and enable / disable options as we see fit: https://istio.io/docs/reference/config/installation-options/

**Comment by ianstanton** [comment]
Update:
* Able to push DAG with CLI
* Test DAG runs successfully
